name: Build with MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Шаг 1: Клонирование репозитория
    - name: Checkout repository
      uses: actions/checkout@v4

    # Шаг 2: Установка MSBuild (опционально, если требуется специфичная версия)
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: 'latest' # Можно указать конкретную версию, например, '16.0' для VS2019 или '17.0' для VS2022

    # Шаг 3: Установка NuGet (если проект использует пакеты NuGet)
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    # Шаг 4: Восстановление пакетов NuGet
    - name: Restore NuGet packages
      run: nuget restore Aimrite.sln
      
    - name: List installed Windows SDKs
      run: dir "C:\Program Files (x86)\Windows Kits\10\Include"

    # Шаг 5: Сборка проекта с помощью MSBuild
    - name: Build with MSBuild
      run: msbuild Aimrite.sln /p:Configuration=Release /p:Platform=x64 /m

    # Шаг 6: (Опционально) Загрузка артефактов сборки
    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: Build-Artifacts
        path: |
          **\Release\x64\* # Укажите путь к вашим артефактам сборки
