name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Путь к файлу решения относительно корня проекта.
  SOLUTION_FILE_PATH: Aimrite.sln

  # Конфигурация сборки.
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Шаг 1: Клонирование репозитория
    - name: Checkout repository
      uses: actions/checkout@v4

    # Шаг 2: Установка MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: 'latest' # Использует последнюю доступную версию Visual Studio

    # Шаг 3: Восстановление NuGet пакетов (если применимо)
    - name: Restore NuGet packages
      run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

    # Шаг 4: Сборка проекта с помощью MSBuild
    - name: Build with MSBuild
      run: msbuild ${{ env.SOLUTION_FILE_PATH }} /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=x64 /m

    # Шаг 5: Просмотр структуры выходных файлов
    - name: List output files
      run: |
        echo "Listing output files..."
        dir Aimrite\x64\Release\
      
    # Шаг 6: Загрузка артефактов сборки
    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: Build-Artifacts
        path: Aimrite\x64\Release\Aimrite.exe
